# Generated by Django 4.2.5 on 2024-02-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0019_alter_figure360view_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figurethinsection',
            old_name='preview',
            new_name='view',
        ),
    ]
