# Generated by Django 4.2.5 on 2024-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0020_rename_preview_figurethinsection_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurethinsection',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='figurethinsection',
            name='view',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='View'),
        ),
    ]
