# Generated by Django 4.2.5 on 2024-02-15 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unique_content', '0021_figurethinsection_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('view', models.ImageField(blank=True, null=True, upload_to='', verbose_name='View')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Preview')),
                ('map_file', models.FileField(upload_to='', verbose_name='Map file')),
                ('made_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update time')),
                ('is_login_required', models.BooleanField(default=True, verbose_name='Login required status')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
            },
        ),
    ]
