# Generated by Django 4.2.5 on 2024-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0022_figuremap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuremap',
            name='map_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Map file'),
        ),
    ]
