# Generated by Django 4.2.5 on 2024-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0023_alter_figuremap_map_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurefromp3din',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='figurethinsection',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor'),
        ),
    ]
