# Generated by Django 4.2.5 on 2024-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0025_alter_figure360view_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figure360view',
            options={'verbose_name': '360 view', 'verbose_name_plural': '360 views'},
        ),
        migrations.AlterModelOptions(
            name='figure360viewinterpretation',
            options={'verbose_name': '360 view interpretation', 'verbose_name_plural': '360 view interpretations'},
        ),
        migrations.AddField(
            model_name='figure360view',
            name='north_correction_angle',
            field=models.FloatField(default=0, verbose_name='North correction'),
        ),
    ]
