# Generated by Django 4.2.5 on 2024-03-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0026_alter_figure360view_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infospotcoordinates',
            name='is_reference',
            field=models.BooleanField(default=True, verbose_name='Is using as reference'),
        ),
    ]
