# Generated by Django 4.2.5 on 2024-03-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0027_infospotcoordinates_is_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='infospotcoordinates',
            name='correction_angle',
            field=models.FloatField(blank=True, null=True, verbose_name='North correction angle'),
        ),
    ]
