# Generated by Django 4.2.5 on 2024-03-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_content', '0028_infospotcoordinates_correction_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='infospotcoordinates',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance between Panorama and InfoSpot'),
        ),
        migrations.AddField(
            model_name='linkspotcoordinates',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance between Panorama_From and Panorama_To'),
        ),
    ]
